version: "3.8"
services:
  php-fpm:
    build: ./docker/php-fpm
    volumes:
      - ./app:/var/www/html
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: symfony
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
