<?php

declare(strict_types=1);

namespace Velorb\LogCleaner\Tests\Helpers;

use PHPUnit\Framework\TestCase as PhpUnitTestCase;

class TestCase extends PhpUnitTestCase
{
    /** @var SampleProvider */
    static protected $sampleProvider;

    public static function setUpBeforeClass(): void
    {
        parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
        self::$sampleProvider = new SampleProvider();
    }
}
